import os
from dotenv import load_dotenv

load_dotenv()

BOT_TOKEN = os.getenv('BOT_API_TOKEN')


PG_URL = os.getenv('PG_URL')
REDIS_URL = os.getenv('REDIS_URL')

IMAGE_HOSTING_KEY = os.getenv('IMAGE_HOSTING_KEY')
IMAGE_HOSTING_URL = os.getenv('IMAGE_HOSTING_URL')


GROK4_FAST_TOKEN = os.getenv('GROK4_FAST')
GPT5_MINI_TOKEN = os.getenv('GPT5MINI')
GEMINI_3_FLASH_PREVIEW_TOKEN = os.getenv('GEMINI_3_FLASH_PREVIEW')
DEEPSEEK_V3_TOKEN = os.getenv('DEEPSEEK_V3')

GROK4_FAST_ID = os.getenv('GROK4_FAST_ID')
GPT5_MINI_ID = os.getenv('GPT5_MINI_ID')
GEMINI_3_FLASH_PREVIEW_ID = os.getenv('GEMINI_3_FLASH_PREVIEW_ID')
DEEPSEEK_V3_ID = os.getenv('DEEPSEEK_V3_ID')


GEMMA3_IMAGES_TOKEN = os.getenv('GEMMA3_IMAGES')


GROK4_FAST_BASE_URL = os.getenv('GROK4_FAST_URL')
GPT5_MINI_BASE_URL = os.getenv('GPT5_MINI_URL')
GEMINI_3_FLASH_PREVIEW_URL = os.getenv('GEMINI_3_FLASH_PREVIEW_URL')
DEEPSEEK_V3_URL = os.getenv('DEEPSEEK_V3_URL')

AES_KEY = os.getenv('AES_KEY')

S3_URL = os.getenv('S3_URL')
BUCKET_NAME = os.getenv('BUCKET_NAME')
S3_ACCESS_KEY = os.getenv('S3_ACCESS_KEY')
S3_SECRET_KEY = os.getenv('S3_SECRET_KEY')
REGION_NAME = os.getenv('REGION_NAME')
S3_URL_DOMAIN = os.getenv('S3_URL_DOMAIN')