MESSAGES = {
    'ru' : {
        'start' : '<b>N​o​d​e​X.​a​i</b> — телеграм-бот с доступом к множеству различным моделям нейросетей.\n\n<b>Используя команду</b> /start <b>вы сразу соглашаетесь с:</b>\n • <a href="https://telegra.ph/Politika-konfidencialnosti-telegram-bota-NodeXai-11-01">Политикой конфиденциальности</a>\n • <a href="https://telegra.ph/OGRANICHENIE-OTVETSTVENNOSTI-telegram-bota-NodeXai-11-01">Политикой ограничения ответственности</a>\n • <a href="https://telegra.ph/POLZOVATELSKOE-SOGLASHENIE-telegarm-bota-NodeXai-11-01">Пользовательским соглашением</a>\n<i>Вы, как пользователь, имеете право отозвать соглашения путем удаления аккаунта через пункт в меню "Опасная зона"</i>\n • <a href="https://telegra.ph/Pravila-ispolzovaniya-telegram-bota-NodeXai-11-01">Правила использования сервиса</a>\n\n<b>Чтобы задать вопрос нейросети — напишите тектовое сообщение</b>\n<b>Меню:</b> /menu\n\n<b>Следите за новостями:</b> @NodeX_project\n<b>Основатель проекта:</b> @ghostfaccee',
        'info' : '<b>N​o​d​e​X.​a​i</b> — проект с открытым исходным кодом, основателем и разработчиком которого является @ghostfaccee.\n\n<b>У проекта имеется лицензия AGPL-3.0</b>, это значит, что он является свободным программным обеспечением, и все его производные версии, включая облачные сервисы, также должны распространяться с открытым кодом.\n\n<b>Этот бот является оригинальным и вы можете доверять ему</b>, так как он неразрывно связан с <a href="https://github.com/NodeX-AI/NodeX.ai">открытым официальным репозиторием</a>.\n\n<b>Ваша переписка с нейросетевой моделью надежно шифруется алгоритмом AES-256-GCM и сохраняется в базе данных</b> <a href="https://telegra.ph/Politika-konfidencialnosti-telegram-bota-NodeXai-11-01">(см. Политику конфиденциальности)</a>.\n\n<b>Сервис предоставляется "как есть" (AS IS). Полные условия, включая ограничение ответственности и правила использования, изложены в</b> <a href="https://telegra.ph/POLZOVATELSKOE-SOGLASHENIE-telegarm-bota-NodeXai-11-01">Пользовательском соглашении</a> <b>и</b> <a href="https://telegra.ph/OGRANICHENIE-OTVETSTVENNOSTI-telegram-bota-NodeXai-11-01">Политике ограничения ответственности</a>.\n\n<b>Вы в полном праве удалить свой аккаунт и отозвать принятые соглашения, используя раздел "Опасная зона" в меню: /menu</b>',
        'faq' : '<b>Ответы на часто задаваемые вопросы вы можете посмотреть по <a href="https://telegra.ph/CHaVo--Telegram-bot-NodeXai-11-01">ссылке</a></b>',
        'models' : '<b>Список доступных моделей:</b>\n • <b>GPT-5 mini</b> - высокоскоростная и мощная компактная модель нового поколения от <i>OpenAI</i>, созданная для мгновенного решения сложных задач с высочайшей точностью.\n • <b>Grok 4 fast</b> - высокоскоростная языковая модель от компании <i>xAI</i>, принадлежащей <b>Илону Маску</b>, оптимизированная для быстрого генеративного взаимодействия.\n • <b>Gemini 3 Flash Preview</b> - самая быстрая и эффективная модель в семействе Gemini от <i>Google</i>, идеальная для задач, требующих почти мгновенного отклика при сохранении высокого интеллектуального уровня.\n • <b>DeepSeek V3.2</b> - новейшая и самая продвинутая модель от компании <i>DeepSeek</i>, предлагающая исключительную глубину понимания, креативность и расширенные возможности работы с кодом и рассуждениями.',
        'change_model' : '<b>Выберите модель:</b>',
        'new_model' : '<b>Модель успешно изменена на {new_model}</b>',
        'menu' : '<b>Меню:</b>',
        'change_language' : '<b>Выберите язык:</b>',
        'new_language' : '<b>Язык успешно изменен на:</b> <i>{lang}</i>',
        'my_profile' : '<b>Ваш профиль</b>\n • <b>ID:</b> <tg-spoiler>{id}</tg-spoiler>\n • <b>Текущая модель:</b> <i>{current_model}</i>\n • <b>Количество сообщений:</b> <i>{message_count}</i>\n • <b>Зарегистрирован:</b> <i>{created_str}</i>\n • <b>Язык:</b> <i>{lang}</i>',
        'statistics' : '<b>Глобальная статистика:</b>\n • <b>Зарегистрированных пользователей:</b> {total_users}\n • <b>Всего сообщений:</b> {total_messages}\n • <b>Популярная модель:</b> {popular_model}',
        'changelog' : '<b>Журнал недавних изменений</b>\n\n <b>Текущая версия: v2.8 - 21.12.2025</b>\n  • <b>Поддержка английского языка для основного интерфейса</b>\n  • <b>Новые модели:</b> <i>Gemini 3 Flash Preview</i> и <i>DeepSeek V3.2</i>\n  • <b>Удалены модели, часто вызывашие ошибки</b>\n  • <b>Удалена функция распознавания изображений из-за ее ненадежности</b>\n\n <b>Предыдущая версия: v2.4 - 07.12.2025</b>\n  • <b>Добавлена новая модель:</b> <i>GPT-5 mini</i>\n  • <b>Добавлен новый шаблон для взаимодействия с OpenAI-совместимым API</b>\n\n <b>Следите за новостями:</b> @NodeX_project',
        'danger_zone' : '<b>Опасная зона. Будьте аккуратнее с выбором.</b>',
        'delete' : '<b>Вы хотите удалить историю сообщений{delete}</b>. Вы уверены в своем выборе?',
        'mes_deleted' : '<b>История ваших сообщение успешно удалена</b>',
        'acc_deleted' : '<b>Ваш аккаунт упешно удален.</b> Чтобы продолжить пользоваться функциями бота нужно зарегистрироваться через команду /start',
        'command_rate_limit' : '⏳ <b>Подождите секунду перед использованием следующей команды</b>',
        'callback_rate_limit' : '⏳ <b>Подождите секунду перед использованием следующей кнопки</b>',
        'remaining_time' : '⏳ <b>Следующий запрос через {remaining_time} секунд</b>',
        'request_processing' : '🔄 <b>Ваш предыдущий запрос еще обрабатывается.</b> Пожалуйста, дождитесь конца обработки предыдущего запроса.',
        'empty_message' : 'Пустой ответ. Вероятно, проблема произошла на стороне провайдера нейросети. Попробуйте позже. Если ошибка повторяется слишком часто направьте ее разработчику по ссылке t.me/NodeX_project?direct'
    },
    'en' : {
        'start' : '<b>N​o​d​e​X.​a​i</b> is a Telegram bot with access to many different neural network models.\n\n<b>By using the command</b> /start <b>you immediately agree to:</b>\n • <a href="https://telegra.ph/Politika-konfidencialnosti-telegram-bota-NodeXai-11-01">Privacy Policy</a>\n • <a href="https://telegra.ph/OGRANICHENIE-OTVETSTVENNOSTI-telegram-bota-NodeXai-11-01">Limitation of Liability Policy</a>\n • <a href="https://telegra.ph/POLZOVATELSKOE-SOGLASHENIE-telegarm-bota-NodeXai-11-01">User Agreement</a>\n<i>You, as a user, have the right to revoke the agreement by deleting your account through the "Danger Zone" menu item</i>\n • <a href="https://telegra.ph/Pravila-ispolzovaniya-telegram-bota-NodeXai-11-01">Rules for using the service</a>\n\n<b>To ask the neural network a question, write a text message</b>\n<b>Menu:</b> /menu\n\n<b>Follow the news:</b> @NodeX_project\n<b>Project founder:</b> @ghostfaccee',
        'info' : '<b>N​o​d​e​X.​a​i</b> is an open-source project founded and developed by @ghostfaccee.\n\n<b>The project is licensed under the AGPL-3.0 license</b>, meaning it is free software, and all derivative versions of it, including cloud services, must also be distributed as open source.\n\n<b>This bot is original and you can trust it</b>, as it is inextricably linked to the <a href="https://github.com/NodeX-AI/NodeX.ai">open official repository</a>.\n\n<b>Your correspondence with the neural network model is securely encrypted with the AES-256-GCM algorithm and stored in the database</b> <a href="https://telegra.ph/Politika-konfidencialnosti-telegram-bota-NodeXai-11-01">(See Privacy Policy)</a>.\n\n<b>The Service is provided "as is" (AS IS). Full terms, including disclaimer and usage rules, are set out in the</b> <a href="https://telegra.ph/POLZOVATELSKOE-SOGLASHENIE-telegarm-bota-NodeXai-11-01">User Agreement</a> <b>and</b> <a href="https://telegra.ph/OGRANICHENIE-OTVETSTVENNOSTI-telegram-bota-NodeXai-11-01">Disclaimer Policy</a>.\n\n<b>You have the full right to delete your account and revoke accepted agreements using the "Danger Zone" section in the menu: /menu</b>',
        'faq' : '<b>You can find answers to frequently asked questions at <a href="https://telegra.ph/CHaVo--Telegram-bot-NodeXai-11-01">link</a></b>',
        'models' : '<b>List of available models:</b>\n • <b>GPT-5 mini</b> - <i>OpenAI\'s</i> next-generation, high-speed, and powerful compact model designed to solve complex problems with pinpoint accuracy in seconds.\n • <b>Grok 4 fast</b> - <i>Elon Musk\'s</i> high-speed language model optimized for fast, generative interactions.\n • <b>Gemini 3 Flash Preview</b> - <i>Google\'s</i> fastest, most efficient Gemini model, ideal for tasks that require near-instantaneous response while maintaining high intelligence.\n • <b>DeepSeek V3.2</b> - <i>DeepSeek\'s</i> latest and most advanced model, delivering exceptional insight, creativity, and advanced code and reasoning.',
        'new_model' : '<b>Model successfully changed to {new_model}</b>',
        'menu' : '<b>Menu:</b>',
        'change_model' : '<b>Select a model</b>',
        'change_language' : '<b>Select a language:</b>',
        'new_language' : '<b>Language successfully changed to:</b> <i>{lang}</i>',
        'my_profile' : '<b>Your profile</b>\n • <b>ID:</b> <tg-spoiler>{id}</tg-spoiler>\n • <b>Current model:</b> <i>{current_model}</i>\n • <b>Number of messages:</b> <i>{message_count}</i>\n • <b>Registered:</b> <i>{created_str}</i>\n • <b>Language:</b> <i>{lang}</i>',
        'statistics' : '<b>Global statistics:</b>\n • <b>Registered users:</b> {total_users}\n • <b>Total messages:</b> {total_messages}\n • <b>Popular model:</b> {popular_model}',
        'changelog' : '<b>Recent Changelog</b>\n\n <b>Current Version: v2.8 - 2025-12-21</b>\n • <b>English language support for the main interface</b>\n • <b>New models:</b> <i>Gemini 3 Flash Preview</i> and <i>DeepSeek V3.2</i>\n • <b>Removed models that frequently caused errors</b>\n • <b>Removed image recognition due to its unreliability</b>\n\n <b>Previous Version: v2.4 - 2025-12-07</b>\n • <b>Added new model:</b> <i>GPT-5 mini</i>\n • <b>Added a new template for interacting with the OpenAI-compatible API</b>\n\n <b>Follow the news:</b> @NodeX_project',
        'danger_zone' : '<b>Danger zone. Be careful with your choices.</b>',
        'delete' : '<b>You want to delete your message history{delete}</b>. Are you sure about your choice?',
        'mes_deleted' : '<b>Your message history has been successfully deleted</b>',
        'acc_deleted' : '<b>Your account has been successfully deleted.</b> To continue using the bot\'s features, you must register using the /start command',
        'command_rate_limit' : '⏳ <b>Wait a second before using the next command</b>',
        'callback_rate_limit' : '⏳ <b>Wait a second before using the next button</b>',
        'remaining_time' : '⏳ <b>Next request in {remaining_time} seconds</b>',
        'request_processing' : '🔄 <b>Your previous request is still being processed.</b> Please wait until the previous request is finished processing.',
        'empty_message' : 'Empty response. The problem likely occurred on the neural network provider\'s side. Try again later. If the error persists too often, please forward it to the developer at t.me/NodeX_project?direct'
    }
}

WARNINGS = {
    'ru' : {
        # middleware/registration_middleware.py
        'not_registered' : 'Вы не зарегистрированы. Зарегистрируйтесь, используя команду /start',
    }
}

ERRORS = {
    'ru' : {
        # services/api_requests.py
        'unexpected' : '❌ Непредвиденная ошибка. Пожалуйста, направьте ошибку разработчику по ссылке t.me/NodeX_project?direct.',
        'timeout' : '❌ Таймаут: запрос обрабатывался слишком долго. Попробуйте сменить модель или подождать и отрпавить запрос снова. Скорее всего, модель в данный момент времени перегружена пользователями и не может ответить на запрос.',
        'api_err' : '❌ Произошла ошибка API. Скорее всего, что-то произошло с API или количество запросов данной модели за день было исчерпано. Вы можете попытаться сменить модель. Пожалуйста, направьте эту ошибку разработчику по ссылке t.me/NodeX_project?direct',
        # middleware/error_logging_middleware.py
        'error_in_handler' : '❌ Произошла ошибка. Пожалуйста, направьте ее разработчику по ссылке t.me/NodeX_project?direct',
        'error_image_host' : '❌ Не удалось загрузить изображение. Пожалуйста, направьте эту ошибку разработчику по ссылке t.me/NodeX_project?direct',
    }
}

def get_warn(warn_key: str, **kwargs) -> str:
    language = 'ru'
    text = WARNINGS[language][warn_key]
    return text.format(**kwargs) if kwargs else text

def get_error(error_key: str, **kwargs) -> str:
    language = 'ru'
    text = ERRORS[language][error_key]
    return text.format(**kwargs) if kwargs else text

def get_text(text_key: str, language: str, **kwargs) -> str:
    text = MESSAGES[language][text_key]
    return text.format(**kwargs) if kwargs else text
